name: file_compression_plus
description: "A comprehensive Flutter package for efficient compression of images and PDFs with support for multiple platforms and formats."
version: 0.0.5
homepage: https://github.com/Tisankan/file_compression_plus
repository: https://github.com/Tisankan/file_compression_plus
issue_tracker: https://github.com/Tisankan/file_compression_plus/issues
documentation: https://github.com/Tisankan/file_compression_plus/blob/main/README.md
topics: [flutter, file-compression, image-compression, pdf-compression, flutter-package]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  syncfusion_flutter_pdf: ^28.2.7
  path: ^1.8.3
  path_provider: ^2.1.2
  universal_io: ^2.2.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  plugin:
    platforms:
      android:
        package: com.tisankan.file_compression_plus
        pluginClass: FileCompressionPlusPlugin
      ios:
        pluginClass: FileCompressionPlusPlugin
      macos:
        pluginClass: FileCompressionPlusPlugin
      web:
        pluginClass: FileCompressionPlusWeb
        fileName: file_compression_plus_web.dart
      windows:
        pluginClass: FileCompressionPlusPlugin
      linux:
        pluginClass: FileCompressionPlusPlugin
